# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_spright'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
