# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
        ('schedule', '0006_occurrence_uid'),
    ]

    operations = [
    ]
