# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('schedule', '0008_auto_20170809_1020'), ('schedule', '0009_event_upstream_url'), ('schedule', '0010_auto_20170810_1108'), ('schedule', '0011_auto_20170810_1150'), ('schedule', '0012_auto_20170810_1150')]

    dependencies = [
        ('schedule', '0007_merge_20170809_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(max_length=512, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='upstream_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upstream_type',
            field=models.CharField(choices=[('eventbrite', 'Eventbrite')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upstream_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
