# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_merge_20170809_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='upstream_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upstream_type',
            field=models.CharField(choices=[('eventbrite', 'Eventbrite')], max_length=24, null=True),
        ),
    ]
