# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20170809_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upstream_url',
            field=models.URLField(null=True),
        ),
    ]
