# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20170809_1020_squashed_0012_auto_20170810_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('live', 'Live')], default='draft', max_length=16),
        ),
    ]
