# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20170810_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asana_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
