# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_event_upstream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
