# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20170810_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upstream_url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
