# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_ensure_unique_upstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='asana_id',
        ),
    ]
