# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_remove_event_asana_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_image',
            field=models.ImageField(max_length=512, null=True, upload_to=''),
        ),
    ]
