# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_event_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_at',
            field=models.DateTimeField(null=True),
        ),
    ]
