# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_event_featured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_in_credits',
            field=models.IntegerField(default=1),
        ),
    ]
