# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_event_cost_in_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='featured_at',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='featured_at',
            field=models.DateTimeField(null=True),
        ),
    ]
