# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20180113_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=35),
        ),
    ]
