# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20180117_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='unlocks_at',
            field=models.DateTimeField(null=True),
        ),
    ]
