# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_occurrence_unlocks_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
    ]
