# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 16:30
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
from ..models import Event

def migrate(*_):
    for event in Event.objects.filter(cost__gt=0, cost__lt=100):
        event.price = event.cost
        event.save()
    for event in Event.objects.filter(cost__gte=100):
        event.price = event.cost / 100
        event.save()
    Event.objects.filter(cost=0).update(price=0)

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_occurrence_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_discount',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='member_discount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='upstream_type',
            field=models.CharField(choices=[('eventbrite', 'Eventbrite'), ('website', 'Website')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=8),
        ),
        migrations.RunPython(migrate),
    ]
