# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models
from ..models import Event
from datetime import datetime, timezone

def adjust_cost(event):
    event.cost = 3000
    event.save()

def migrate(*_):
    now = datetime.now(timezone.utc)
    for event in Event.objects.filter(cost=3500, start__gte=now):
        adjust_cost(event)
    for event in Event.objects.filter(cost=3500, rule__isnull=False, end_recurring_period__isnull=True):
        adjust_cost(event)
    for event in Event.objects.filter(cost=3500, rule__isnull=False, end_recurring_period__gt=now):
        adjust_cost(event)

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_occurrence_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_discount',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='member_discount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='upstream_type',
            field=models.CharField(choices=[('eventbrite', 'Eventbrite'), ('website', 'Website')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=30),
        ),
        migrations.RunPython(migrate),
    ]
