# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_credits_to_dollars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upstream_url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
