# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20180418_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upstream_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
