# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    replaces = [('schedule', '0024_auto_20180418_1421'), ('schedule', '0025_auto_20180418_1614'), ('schedule', '0026_event_primary_category')]

    dependencies = [
        ('schedule', '0023_auto_20180418_1334'),
        ('main', '0078_eventcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', related_query_name='events', to='main.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('class', 'Class'), ('event', 'Event'), ('collection', 'Collection')], default='class', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='signup_window',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_events', related_query_name='primary_events', to='main.EventCategory'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='children', to='schedule.Event'),
        ),
    ]
