# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 18:28
from __future__ import unicode_literals

from django.db import migrations
from ..models import Event


def migrate(*_):
    Event.objects.filter(host_id__isnull=True).update(kind='event')
    Event.objects.filter(host_id__in=[1250, 1044]).update(kind='event')


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_categories_n_stuff'),
    ]

    operations = [
        migrations.RunPython(migrate),
    ]
