# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_initial_event_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('class', 'Class'), ('event', 'Event'), ('festival', 'Festival'), ('urban_retreat', 'Urban retreat')], default='class', max_length=16),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
