# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_uuid1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='uid',
            new_name='uuid',
        ),
    ]
