# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_uuid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='slot_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='slot_duration',
            field=models.IntegerField(default=0),
        ),
    ]
