# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_timeslots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='host',
            new_name='o_host',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='description',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='title',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='o_description',
            field=models.TextField(db_column='description', null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='o_title',
            field=models.CharField(db_column='title', max_length=255, null=True),
        ),
    ]
