# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_inheritance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='o_host',
            field=models.ForeignKey(db_column='host', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
