# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_event_waitlist_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='o_image',
            field=models.ImageField(db_column='image', max_length=512, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='o_waitlist_enabled',
            field=models.NullBooleanField(db_column='waitlist_enabled'),
        ),
    ]
