# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_inheritance2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='template_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
