# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_revenue_coupon'),
        ('schedule', '0034_remove_event_cost_in_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.EventCoupon'),
        ),
    ]
