# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_eventfamily'),
        ('schedule', '0035_occurrence_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.EventFamily'),
        ),
    ]
