# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0036_event_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
