# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0037_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.AddField(
            model_name='event',
            name='price_in_credits',
            field=models.IntegerField(default=3),
        ),
    ]
