# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-24 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0038_price_in_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='o_location',
            field=models.TextField(db_column='location', null=True),
        ),
    ]
