# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models
from schedule.models import Event

def migrate(*_):
    Event.objects.filter(kind='urban_retreat').update(kind='festival')

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_occurrence_o_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('class', 'class'), ('event', 'event'), ('festival', 'festival'), ('day pass', 'day pass')], default='class', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('live', 'live')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='upstream_type',
            field=models.CharField(choices=[('eventbrite', 'eventbrite'), ('website', 'website')], max_length=24, null=True),
        ),
        migrations.RunPython(migrate)
    ]
