# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0040_auto_20190125_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fitness_level',
            field=models.CharField(choices=[('low intensity', 'low intensity'), ('high intensity', 'high intensity'), ('restorative', 'restorative')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='series_type',
            field=models.CharField(choices=[('regularly scheduled', 'regularly scheduled'), ('local popup', 'local popup'), ('visiting popup', 'visiting popup')], max_length=32, null=True),
        ),
    ]
